# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.network :private_network, ip: "10.2.0.2"
  config.ssh.forward_agent = true
  config.vm.host_name = 'vagrant.test'

   config.vm.provider :virtualbox do |vb|
     #vb.gui = true
     vb.customize ["modifyvm", :id, "--memory", "1024"]
   end
end
